"""Embed the fetched cap sheets into the chat page.

    python -m serving.build_chat

Reads `data/capsheets/<season>/<TEAM>.json`, renders each roster into the exact format the
model was trained to read, and writes the data into `serving/chat.html` between marker
comments. The page stays a single file you can double-click -- no server, no build step at
view time, works offline apart from asking the model itself.

Rendering reuses `datagen.capsheet`, so what the picker loads is byte-identical in shape to
what the training examples looked like. A different format here would be testing the model
on something it never saw.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from capengine.constants import SEASONS, get_season
from capengine.trace import usd
from datagen.capsheet import constants_block

TEAM_NAMES = {
    "ATL": "Atlanta Hawks", "BOS": "Boston Celtics", "BKN": "Brooklyn Nets",
    "CHA": "Charlotte Hornets", "CHI": "Chicago Bulls", "CLE": "Cleveland Cavaliers",
    "DAL": "Dallas Mavericks", "DEN": "Denver Nuggets", "DET": "Detroit Pistons",
    "GSW": "Golden State Warriors", "HOU": "Houston Rockets", "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers", "LAL": "Los Angeles Lakers", "MEM": "Memphis Grizzlies",
    "MIA": "Miami Heat", "MIL": "Milwaukee Bucks", "MIN": "Minnesota Timberwolves",
    "NOP": "New Orleans Pelicans", "NYK": "New York Knicks", "OKC": "Oklahoma City Thunder",
    "ORL": "Orlando Magic", "PHI": "Philadelphia 76ers", "PHX": "Phoenix Suns",
    "POR": "Portland Trail Blazers", "SAC": "Sacramento Kings", "SAS": "San Antonio Spurs",
    "TOR": "Toronto Raptors", "UTA": "Utah Jazz", "WAS": "Washington Wizards",
}

START = "// === CAPSHEET DATA (generated by serving/build_chat.py) ==="
END = "// === END CAPSHEET DATA ==="


def render(sheet: dict) -> str:
    """Render one cap sheet exactly as the training data presented them."""
    k = get_season(sheet["season"])
    incentives = sheet.get("unlikely_incentives") or {}

    lines = [
        constants_block(k),
        "",
        f"{sheet['team'].upper()} -- {sheet['season']} CAP SHEET",
        "| Player | Salary | Unlikely incentives | Years left |",
        "| --- | ---: | ---: | ---: |",
    ]
    for player in sheet["players"]:
        bonus = incentives.get(player["name"])
        lines.append(
            f"| {player['name']} | {usd(player['salary'])} | "
            f"{usd(bonus) if bonus else '--'} | -- |"
        )

    lines.append("")
    if sheet.get("dead_money"):
        lines.append(f"Dead money: {usd(sheet['dead_money'])}")
    lines.append(f"Roster count: {len(sheet['players'])}")
    if sheet.get("is_repeater"):
        lines.append("Repeater taxpayer: yes")
    if sheet.get("hard_capped_at"):
        lines.append(f"Hard cap: {sheet['hard_capped_at']}")
    return "\n".join(lines)


def note(sheet: dict) -> str:
    """The provenance line shown under the picker, including any data caveat."""
    parts = [f"Source: {sheet['source']} · fetched {sheet['fetched']}"]
    if sheet.get("caveat"):
        parts.append(sheet["caveat"])
    if sheet.get("second_apron_space") is not None:
        space = sheet["second_apron_space"]
        parts.append(
            f"Site states second apron space {usd(space)}"
            if space >= 0
            else f"Site states this team is {usd(-space)} OVER the second apron"
        )
    return " — ".join(parts)


def collect(data_dir: Path) -> dict:
    seasons: dict[str, dict] = {}
    for season in sorted(SEASONS, reverse=True):
        season_dir = data_dir / season
        if not season_dir.exists():
            continue
        teams = {}
        for path in sorted(season_dir.glob("*.json")):
            sheet = json.loads(path.read_text())
            teams[path.stem] = {
                "name": TEAM_NAMES.get(path.stem, sheet.get("team", path.stem)),
                "sheet": render(sheet),
                "note": note(sheet),
            }
        if teams:
            seasons[season] = teams
    return seasons


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, default=Path("data/capsheets"))
    parser.add_argument("--page", type=Path, default=Path("serving/chat.html"))
    args = parser.parse_args()

    seasons = collect(args.data)
    if not seasons:
        raise SystemExit(
            f"No cap sheets under {args.data}. Fetch them first:\n"
            "  python -m datagen.fetch_capsheets --season 2026-27\n"
            "  python -m datagen.fetch_historical"
        )

    payload = f"{START}\nconst CAPSHEETS = {json.dumps(seasons, ensure_ascii=False)};\n{END}"
    page = args.page.read_text()
    if START not in page:
        raise SystemExit(f"{args.page} has no data markers; expected line: {START}")
    updated = re.sub(
        re.escape(START) + r".*?" + re.escape(END), lambda _: payload, page, flags=re.DOTALL
    )
    args.page.write_text(updated)

    total = sum(len(t) for t in seasons.values())
    print(f"embedded {total} cap sheets into {args.page}")
    for season, teams in seasons.items():
        print(f"  {season}: {len(teams)} teams")


if __name__ == "__main__":
    main()
